#! /bin/bash

cd /cudd-3val && ./configure --enable-silent-rules --enable-obj --enable-shared && make -j4 && make install

cd /Q3B

cmake -B build -DANTLR_EXECUTABLE=/usr/share/java/antlr-4.11.1-complete.jar
cmake --build build -j4
cd build && make test