version: '2'
services:
  q3b:
    container_name: q3b
    build:
        context: .
    tty: true
    stdin_open: true
    volumes:
      - "./cudd-3val:/cudd-3val"
      - "./Q3B:/Q3B"
      - "./testing:/testing"
      - "./helpers:/helpers"
    restart: "no"
